# Generated by Django 5.2 on 2025-05-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_number',
            field=models.CharField(blank=True, default='기본값', max_length=20, null=True),
        ),
    ]
